global:
  smtp_smarthost: "mailhog:1025"
  smtp_from: "email@example.com"
route:
  receiver: example-email
  group_by: [alertname]
receivers:
  - name: example-email
    email_configs:
      - to: "email@example.com"
